"""
=================================================================
 🚀 File: train.py
 ✨ Purpose: Advanced Machine Learning Operations and Processing
 📅 Last Updated: 2026
=================================================================
"""

import os
import pandas as pd
import joblib
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from src.preprocessing import get_full_pipeline
import logging
from pathlib import Path

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# ==================================================
# Function Definition
# ==================================================
def train_model(data_path: str, model_save_path: str):
    """
    Trains the ML pipeline and saves the artifact.
    """
    logger.info(f"Loading data from {data_path}")
    df = pd.read_csv(data_path)
    
    # Define features and target
    TARGET = 'Churn'
    
    # Drop customerID as it's not a predictive feature
    X = df.drop(columns=[TARGET, 'customerID'])
    # Convert target to binary
    y = df[TARGET].map({'Yes': 1, 'No': 0})
    
    # Define numeric and categorical features based on remaining columns
    numeric_features = ['tenure', 'MonthlyCharges', 'TotalCharges']
    categorical_features = [col for col in X.columns if col not in numeric_features]
    
    # We include custom engineered features generated by FeatureEngineer in the lists if they need subsequent processing
    numeric_features.extend(['AvgMonthlyCharge', 'IsNewCustomer']) 
    
    logger.info("Splitting data into train and test sets...")
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
    
    # Define the base model
    model = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42, class_weight='balanced')
    
    # Get the full pipeline (feature engineering -> preprocessing -> model)
    pipeline = get_full_pipeline(numeric_features, categorical_features, model)
    
    logger.info("Training the model pipeline...")
    # This single fit call handles all transformations and model training!
    pipeline.fit(X_train, y_train)
    
    # Evaluate briefly
    train_score = pipeline.score(X_train, y_train)
    test_score = pipeline.score(X_test, y_test)
    logger.info(f"Train Accuracy: {train_score:.4f}")
    logger.info(f"Test Accuracy: {test_score:.4f}")
    
    # Ensure save directory exists
    Path(os.path.dirname(model_save_path)).mkdir(parents=True, exist_ok=True)
    
    # Save the FULL PIPELINE, not just the model.
    # This is critical for ML Engineering! When we deploy, we just load this one object.
    logger.info(f"Saving pipeline artifact to {model_save_path}")
    joblib.dump(pipeline, model_save_path)
    logger.info("Training complete.")

if __name__ == "__main__":
    # Ensure data exists, if not generate it
    data_file = os.path.join(os.path.dirname(__file__), "../data/raw/churn_data.csv")
    if not os.path.exists(data_file):
        from src.data_ingestion import ingest_data
        ingest_data(os.path.dirname(data_file))
        
    model_file = os.path.join(os.path.dirname(__file__), "../models/churn_pipeline.pkl")
    train_model(data_file, model_file)
 